name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: https://index.docker.io/v1/
        # Username used to log against the Docker registry
        username: ${{ secrets.dockerhub_username }}
        # Password or personal access token used to log against the Docker registry
        password:  ${{ secrets.dockerhub_password }}
        # Log out from the Docker registry at the end of a job
        logout: false
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
       push: true
       tags: index.docker.io/ds21m013/covid-dashboard:${{ github.sha }}
       file: ./Dockerfile
       
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.5
      with:
        # Name of the Azure Web App
        app-name: ds21m013-covid-dashboard
        publish-profile: ${{ AZUREPUBLISHDATA }}
        images: index.docker.io/ds21m013/covid-dashboard:${{ github.sha }}
